import MetaTrader5 as mt5
import pandas as pd
import pandas_ta as ta
import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import logging

class MLHybridStrategy:
    def __init__(self, symbol, timeframe, train_bars=10000):
        self.symbol = symbol
        self.timeframe = timeframe
        self.train_bars = train_bars
        self.model = XGBClassifier(
            n_estimators=100, 
            learning_rate=0.05, 
            max_depth=4, 
            random_state=42,
            eval_metric='logloss'
        )
        self.is_trained = False
        self.features = ['RSI_14', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 
                         'ATRr_14', 'BBL_20_2.0_2.0', 'BBM_20_2.0_2.0', 'BBU_20_2.0_2.0', 
                         'EMA_50', 'EMA_200']
                         
    def get_data(self, num_bars):
        """Fetch historical data from MT5"""
        rates = mt5.copy_rates_from_pos(self.symbol, self.timeframe, 0, num_bars)
        if rates is None:
            logging.error(f"Failed to fetch {num_bars} bars for {self.symbol}")
            return pd.DataFrame()
            
        df = pd.DataFrame(rates)
        df['time'] = pd.to_datetime(df['time'], unit='s')
        return df

    def calculate_features(self, df):
        """Calculate Technical Indicators for Machine Learning"""
        if df.empty:
            return df
            
        # Momentum & Oscillators
        df.ta.rsi(length=14, append=True)
        df.ta.macd(fast=12, slow=26, signal=9, append=True)
        
        # Volatility
        df.ta.atr(length=14, append=True)
        df.ta.bbands(length=20, std=2.0, append=True)
        
        # Trend
        df.ta.ema(length=50, append=True)
        df.ta.ema(length=200, append=True)
        
        # Price Action relative features
        df['Close_to_EMA50'] = df['close'] - df['EMA_50']
        df['Close_to_EMA200'] = df['close'] - df['EMA_200']
        
        # Drop NaN values generated by rolling calculations
        df.dropna(inplace=True)
        return df

    def prepare_training_data(self):
        """Fetch data, calculate features, and create labels"""
        logging.info(f"Fetching {self.train_bars} bars for training...")
        df = self.get_data(self.train_bars)
        df = self.calculate_features(df)
        
        if df.empty:
            return None, None
            
        # Create Target Label: 1 if close price explicitly higher after 3 candles
        # Shift(-3) means looking 3 candles into the future
        future_close = df['close'].shift(-3)
        
        # 1 if price goes up, 0 if price goes down
        df['Target'] = (future_close > df['close']).astype(int)
        
        # Drop the last row(s) which will have NaN targets
        df.dropna(inplace=True)
        
        # Add dynamic features to the list of features we care about
        extended_features = self.features + ['Close_to_EMA50', 'Close_to_EMA200']
        
        X = df[extended_features]
        y = df['Target']
        
        return X, y

    def train(self):
        """Train the XGBoost model on historical MT5 data"""
        X, y = self.prepare_training_data()
        if X is None or len(X) < 100:
            logging.error("Not enough data to train model.")
            return False
            
        # Split data chronologically (don't shuffle time series!)
        split_idx = int(len(X) * 0.8)
        X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
        y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]
        
        logging.info("Training XGBoost Classifier...")
        self.model.fit(X_train, y_train)
        
        predictions = self.model.predict(X_test)
        accuracy = accuracy_score(y_test, predictions)
        logging.info(f"Model Trained! Out-of-Sample Accuracy: {accuracy:.2f}")
        
        self.is_trained = True
        return True

    def get_signal(self):
        """
        Analyze current data, run model prediction, and return signal + ATR for risk.
        Returns: (signal (str), atr (float))
        """
        if not self.is_trained:
            logging.warning("Model not trained yet! Attempting to train...")
            if not self.train():
                return "HOLD", 0.0
                
        # Fetch the latest 300 bars to ensure all indicators can be calculated
        df = self.get_data(300)
        df = self.calculate_features(df)
        
        if df.empty or len(df) < 1:
            return "HOLD", 0.0
            
        # Get the most recently completely closed candle
        curr_candle = df.iloc[-1]
        extended_features = self.features + ['Close_to_EMA50', 'Close_to_EMA200']
        
        # Prepare input vector for the model
        X_live = curr_candle[extended_features].to_frame().T.astype(float)
        
        # The model returns probabilities: [prob_down (0), prob_up (1)]
        probabilities = self.model.predict_proba(X_live)[0]
        prob_down = probabilities[0]
        prob_up = probabilities[1]
        
        current_atr = curr_candle['ATRr_14']
        
        # Only take a trade if the model is highly confident (> 65% probability)
        # AND if it aligns with the macro trend (EMA 200)
        close_price = curr_candle['close']
        ema_200 = curr_candle['EMA_200']
        
        CONFIDENCE_THRESHOLD = 0.65
        
        if prob_up > CONFIDENCE_THRESHOLD and close_price > ema_200:
            return "BUY", current_atr
            
        elif prob_down > CONFIDENCE_THRESHOLD and close_price < ema_200:
            return "SELL", current_atr
            
        return "HOLD", current_atr
